### ISSUE TITLE
What would happen if a worker machine crashes?

### ISSUE THREAD

**Issue by Baka-14** [code100x/neet-results-2024#1]
Hey, 

First of all great video, I was just curious to know if there is any logic here that looks out for when, let's say a worker machine takes a job and then supporse crashes ? Will it be assigned to someone else after a timeout ?

**Comment by bhupixb** [comment]
As per the code, if a worker dies while processing some application(s) number, it will be lost forever and never be retried.

A simple solution(rough idea) to this could be that we can have a reconciler that periodically(say every 5min) checks in DB for entries:
  1. that have been picked by a worker.
  2. Older than some time ~2min(assuming in the worst case the latency for a worker is 2min).
  3. and the score is not yet updated.
  4. Mark such rows as unsolved again, so that the Orchestrator can give assign this application to other workers.

**Comment by Baka-14** [comment]
So it would do like a linear search over all the pick up times with the current time and check if the worker has solved the problem, got it. If no one is working on it can i give it a try ?

**Comment by hkirat** [comment]
Yeah it wont be retried, thats why there's a `pickupTime` so if something isnt solved for > 2 hours you can pick it up again

**Comment by bhupixb** [comment]
yup. A few optimizations to avoid using linear search.
Since all **processed** application numbers will have _pickUpTime_ as not null, scanning these rows(`SELECT * FROM application_number where pickup_time is not null`) can be expensive(imagine we inserted 2.5 million roll numbers initially in our DB).

What we can do is introduce a new column _state_ in our ApplicationNumber table to represent the state of the application like IN PROGRESS, COMPLETED.

Initially, the state can be PENDING.
1. When a worker picks up an application number, we will mark the state as IN PROGRESS.
2. In the reconciler, we can pick all rows with state=INPROGRESS. To speed up the query, we can have an index on state column which will help us to quickly filter out these rows. If we are running say 1000 machines and each minute 100 machines are crashing, then in a 5-minute period, we have to re-process only 500 application numbers which is a very small numer.
